set(_CATKIN_CURRENT_PACKAGE "autocamera")
set(autocamera_MAINTAINER "shahab <shahab.eslamian@wayne.edu>")
set(autocamera_DEPRECATED "")
set(autocamera_VERSION "0.0.0")
set(autocamera_BUILD_DEPENDS )
set(autocamera_RUN_DEPENDS )
set(autocamera_BUILDTOOL_DEPENDS "catkin")