# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_control_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(672, 613)
        Dialog.setMinimumSize(QtCore.QSize(672, 613))
        Dialog.setMaximumSize(QtCore.QSize(1000, 1000))
        Dialog.setMouseTracking(True)
        self.groupBoxOperationMode = QtWidgets.QGroupBox(Dialog)
        self.groupBoxOperationMode.setGeometry(QtCore.QRect(10, 230, 161, 71))
        self.groupBoxOperationMode.setObjectName("groupBoxOperationMode")
        self.radioButtonSimulation = QtWidgets.QRadioButton(self.groupBoxOperationMode)
        self.radioButtonSimulation.setGeometry(QtCore.QRect(10, 20, 116, 22))
        self.radioButtonSimulation.setObjectName("radioButtonSimulation")
        self.radioButtonHardware = QtWidgets.QRadioButton(self.groupBoxOperationMode)
        self.radioButtonHardware.setGeometry(QtCore.QRect(10, 40, 116, 22))
        self.radioButtonHardware.setObjectName("radioButtonHardware")
        self.groupBoxCameraControlMethod = QtWidgets.QGroupBox(Dialog)
        self.groupBoxCameraControlMethod.setGeometry(QtCore.QRect(10, 300, 171, 151))
        self.groupBoxCameraControlMethod.setAutoFillBackground(False)
        self.groupBoxCameraControlMethod.setObjectName("groupBoxCameraControlMethod")
        self.radioButtonAutocamera = QtWidgets.QRadioButton(self.groupBoxCameraControlMethod)
        self.radioButtonAutocamera.setGeometry(QtCore.QRect(10, 40, 116, 22))
        self.radioButtonAutocamera.setObjectName("radioButtonAutocamera")
        self.radioButtonClutchAndMove = QtWidgets.QRadioButton(self.groupBoxCameraControlMethod)
        self.radioButtonClutchAndMove.setGeometry(QtCore.QRect(10, 60, 151, 22))
        self.radioButtonClutchAndMove.setObjectName("radioButtonClutchAndMove")
        self.radioButtonJoystick = QtWidgets.QRadioButton(self.groupBoxCameraControlMethod)
        self.radioButtonJoystick.setGeometry(QtCore.QRect(10, 80, 141, 22))
        self.radioButtonJoystick.setObjectName("radioButtonJoystick")
        self.radioButtonTeleop = QtWidgets.QRadioButton(self.groupBoxCameraControlMethod)
        self.radioButtonTeleop.setGeometry(QtCore.QRect(10, 20, 116, 22))
        self.radioButtonTeleop.setObjectName("radioButtonTeleop")
        self.radioButtonOculus = QtWidgets.QRadioButton(self.groupBoxCameraControlMethod)
        self.radioButtonOculus.setGeometry(QtCore.QRect(10, 100, 141, 22))
        self.radioButtonOculus.setObjectName("radioButtonOculus")
        self.radioButtonClutchless = QtWidgets.QRadioButton(self.groupBoxCameraControlMethod)
        self.radioButtonClutchless.setGeometry(QtCore.QRect(10, 120, 141, 22))
        self.radioButtonClutchless.setObjectName("radioButtonClutchless")
        self.groupBoxPower = QtWidgets.QGroupBox(Dialog)
        self.groupBoxPower.setGeometry(QtCore.QRect(10, 20, 120, 181))
        self.groupBoxPower.setObjectName("groupBoxPower")
        self.pushButtonHome = QtWidgets.QPushButton(self.groupBoxPower)
        self.pushButtonHome.setGeometry(QtCore.QRect(10, 20, 98, 27))
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.pushButtonPowerOff = QtWidgets.QPushButton(self.groupBoxPower)
        self.pushButtonPowerOff.setGeometry(QtCore.QRect(10, 80, 98, 27))
        self.pushButtonPowerOff.setObjectName("pushButtonPowerOff")
        self.pushButtonExit = QtWidgets.QPushButton(self.groupBoxPower)
        self.pushButtonExit.setGeometry(QtCore.QRect(10, 140, 98, 27))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonPowerOn = QtWidgets.QPushButton(self.groupBoxPower)
        self.pushButtonPowerOn.setGeometry(QtCore.QRect(10, 50, 98, 27))
        self.pushButtonPowerOn.setObjectName("pushButtonPowerOn")
        self.pushButtonReset = QtWidgets.QPushButton(self.groupBoxPower)
        self.pushButtonReset.setGeometry(QtCore.QRect(10, 110, 98, 27))
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.groupBoxAutocameraParams = QtWidgets.QGroupBox(Dialog)
        self.groupBoxAutocameraParams.setGeometry(QtCore.QRect(220, 20, 461, 80))
        self.groupBoxAutocameraParams.setObjectName("groupBoxAutocameraParams")
        self.horizontalSliderInnerzone = QtWidgets.QSlider(self.groupBoxAutocameraParams)
        self.horizontalSliderInnerzone.setGeometry(QtCore.QRect(138, 23, 231, 29))
        self.horizontalSliderInnerzone.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderInnerzone.setObjectName("horizontalSliderInnerzone")
        self.horizontalSliderDeadzone = QtWidgets.QSlider(self.groupBoxAutocameraParams)
        self.horizontalSliderDeadzone.setGeometry(QtCore.QRect(138, 53, 231, 29))
        self.horizontalSliderDeadzone.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderDeadzone.setObjectName("horizontalSliderDeadzone")
        self.labelInnerzoneValue = QtWidgets.QLabel(self.groupBoxAutocameraParams)
        self.labelInnerzoneValue.setGeometry(QtCore.QRect(378, 26, 41, 17))
        self.labelInnerzoneValue.setObjectName("labelInnerzoneValue")
        self.labelDeadzoneValue = QtWidgets.QLabel(self.groupBoxAutocameraParams)
        self.labelDeadzoneValue.setGeometry(QtCore.QRect(378, 55, 41, 17))
        self.labelDeadzoneValue.setObjectName("labelDeadzoneValue")
        self.label_3 = QtWidgets.QLabel(self.groupBoxAutocameraParams)
        self.label_3.setGeometry(QtCore.QRect(10, 29, 121, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBoxAutocameraParams)
        self.label_4.setGeometry(QtCore.QRect(10, 56, 131, 20))
        self.label_4.setObjectName("label_4")
        self.pushButtonRecord = QtWidgets.QPushButton(Dialog)
        self.pushButtonRecord.setGeometry(QtCore.QRect(13, 565, 131, 27))
        self.pushButtonRecord.setObjectName("pushButtonRecord")
        self.labelSubjectInfo = QtWidgets.QLabel(Dialog)
        self.labelSubjectInfo.setGeometry(QtCore.QRect(90, 538, 111, 20))
        self.labelSubjectInfo.setText("")
        self.labelSubjectInfo.setObjectName("labelSubjectInfo")
        self.labelSubjectNumber = QtWidgets.QLabel(Dialog)
        self.labelSubjectNumber.setGeometry(QtCore.QRect(12, 515, 131, 16))
        self.labelSubjectNumber.setObjectName("labelSubjectNumber")
        self.spinBoxSubjectNumber = QtWidgets.QSpinBox(Dialog)
        self.spinBoxSubjectNumber.setGeometry(QtCore.QRect(19, 535, 60, 27))
        self.spinBoxSubjectNumber.setMinimum(1)
        self.spinBoxSubjectNumber.setMaximum(20)
        self.spinBoxSubjectNumber.setObjectName("spinBoxSubjectNumber")
        self.labelPatternNumber = QtWidgets.QLabel(Dialog)
        self.labelPatternNumber.setGeometry(QtCore.QRect(12, 455, 131, 16))
        self.labelPatternNumber.setObjectName("labelPatternNumber")
        self.spinBoxPatternNumber = QtWidgets.QSpinBox(Dialog)
        self.spinBoxPatternNumber.setGeometry(QtCore.QRect(20, 475, 60, 27))
        self.spinBoxPatternNumber.setMinimum(1)
        self.spinBoxPatternNumber.setMaximum(5)
        self.spinBoxPatternNumber.setObjectName("spinBoxPatternNumber")
        self.labelTimer = QtWidgets.QLabel(Dialog)
        self.labelTimer.setGeometry(QtCore.QRect(159, 570, 66, 17))
        self.labelTimer.setObjectName("labelTimer")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "da Vinci Camera Controller"))
        self.groupBoxOperationMode.setTitle(_translate("Dialog", "Operation Mode"))
        self.radioButtonSimulation.setText(_translate("Dialog", "Simulation"))
        self.radioButtonHardware.setText(_translate("Dialog", "Hardware"))
        self.groupBoxCameraControlMethod.setTitle(_translate("Dialog", "Camera Control Method"))
        self.radioButtonAutocamera.setText(_translate("Dialog", "Autocamera"))
        self.radioButtonClutchAndMove.setText(_translate("Dialog", "Clutch and Move"))
        self.radioButtonJoystick.setText(_translate("Dialog", "Joystick Control"))
        self.radioButtonTeleop.setText(_translate("Dialog", "Teleop"))
        self.radioButtonOculus.setText(_translate("Dialog", "Oculus"))
        self.radioButtonClutchless.setText(_translate("Dialog", "Clutchless System"))
        self.groupBoxPower.setTitle(_translate("Dialog", "Power"))
        self.pushButtonHome.setText(_translate("Dialog", "Home"))
        self.pushButtonPowerOff.setText(_translate("Dialog", "Power Off"))
        self.pushButtonExit.setText(_translate("Dialog", "Exit"))
        self.pushButtonPowerOn.setText(_translate("Dialog", "Power On"))
        self.pushButtonReset.setText(_translate("Dialog", "Reset"))
        self.groupBoxAutocameraParams.setTitle(_translate("Dialog", "Autocamera Zoom Parameters"))
        self.labelInnerzoneValue.setText(_translate("Dialog", "0"))
        self.labelDeadzoneValue.setText(_translate("Dialog", "0"))
        self.label_3.setText(_translate("Dialog", "Inner Zone Radius"))
        self.label_4.setText(_translate("Dialog", "Dead Zone Radius"))
        self.pushButtonRecord.setText(_translate("Dialog", "Record"))
        self.labelSubjectNumber.setText(_translate("Dialog", "Subject Number"))
        self.labelPatternNumber.setText(_translate("Dialog", "Pattern Number"))
        self.labelTimer.setText(_translate("Dialog", "0:0:0"))

